plugins {
  id 'com.android.library'
}

android {
  namespace "com.facebook.shimmer"
  compileSdk 35//Version versions.compileSdk

  defaultConfig {
    minSdk 19//Version versions.minSdk
    multiDexEnabled true
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  lintOptions {
    abortOnError false
    checkReleaseBuilds false
  }
}

dependencies {
  api 'com.github.mozhimen.ALibKit_Jetpack:annotation:0.0.7'
}
