/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

apply plugin: 'com.android.library'

android {
  namespace "com.facebook.shimmer"
  compileSdk 35//Version versions.compileSdk

  defaultConfig {
    minSdk 19//Version versions.minSdk
    multiDexEnabled true
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  api project(":ALibKit_Jetpack:annotation")
}

//apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
